---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: centos7
    box: centos/7
provisioner:
  name: ansible
  playbooks:
    converge: ../playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: vagrant
verifier:
  name: testinfra
  directory: ../tests/
  lint:
    name: flake8
  options:
    # show which tests where executed in test output
    v: 1
